# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [3]:
import numpy as np

In [ ]:
# ejercicio 1
a1 = np.array([1, 2, 3, 4])

arr0 =np.all(a1 != 0)

arr0

np.True_

In [6]:
# ejercicio 2

a2 = np.array([0, 0, 2, 0])

arrNot0 = np.any(a2 != 0)

arrNot0



np.True_

In [7]:
# ejercicio 3

a3 = np.array([1, 2, np.nan, np.inf])

valoresFaltentes = np.isnan(a3) | np.isinf(a3)
valoresFaltentes

array([False, False,  True,  True])

In [8]:
# ejercicio 4

a4 = np.array([1, 2, np.inf])

valoresInf = np.isinf(a4)
valoresInf

array([False, False,  True])

In [9]:
# ejercicio 5

a5 = np.array([1, np.nan, 3])

valoresFalt = np.isnan(a5)
valoresFalt

array([False,  True, False])

In [11]:
# ejercicio 6

a6 = np.array([1, 3, 5])
b6 = np.array([2, 3, 4])

print("a > b :", a6 > b6)
print("a >= b:", a6 >= b6)
print("a < b :", a6 < b6)
print("a <= b:", a6 <= b6)

a > b : [False False  True]
a >= b: [False  True  True]
a < b : [ True False False]
a <= b: [ True  True False]


In [12]:
# ejercicio 7

# 7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.

a7 = np.array([1, 7, 13, 105])

a7_memoria = a7.nbytes
a7_memoria

32

In [29]:
# ejercicio 8

# 8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.

a8_ceros = np.zeros(10)
a8_unos = np.ones(10)
a8_cincos = np.full(10, 5)

a8_ceros, a8_unos, a8_cincos


(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))

In [30]:
# ejercicio 9

# 9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.

a9 = np.arange(30, 71)
a9

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [31]:

# ejercicio 10

# 10. Crea un arreglo que contenga los números pares entre 30 y 70.

a10 = np.arange(30, 71, 2)
a10

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [32]:

# ejercicio 11

# 11. Crea una matriz identidad de 3x3.

a11 = np.eye(3)
a11

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:

# ejercicio 12

# 12. Genera un número aleatorio entre 0 y 1.

a12 = np.random.rand()
a12


0.6872207193189482

In [35]:

# ejercicio 13

# 13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.

a13 = np.random.randn(15)
a13



array([ 1.24590849, -0.70812646, -0.11422659, -2.2172938 ,  0.00532937,
        0.04975098, -1.08028664,  1.8378461 , -1.45013496, -0.11262265,
        0.2109711 ,  0.47272942, -0.12177821, -1.58217838, -2.57635158])

In [36]:

# ejercicio 14

# 14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.

a14 = np.arange(15, 56)
a14[1:-1]


array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [37]:

# ejercicio 15

# 15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.

a15 = np.linspace(5, 50, 10)
a15



array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [40]:

# ejercicio 16

# 16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.

a16 = np.arange(0, 21)
a16[9:16] = -a16[9:16]

a16



array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [42]:

# ejercicio 17

# 17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.


a17 = np.array([1, 2, 3])
a17.tolist()



[1, 2, 3]

In [44]:

# ejercicio 18

# 18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.

a18 = [1, 2, 3]

a18_array = np.array(a18)

a18_array.astype(np.ndarray)



array([1, 2, 3], dtype=object)

In [45]:

# ejercicio 19

# 19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.


m = np.array([[1, 2], [3, 4]])
pares = (m % 2 == 0)
pares





array([[False,  True],
       [False,  True]])

In [46]:

# ejercicio 20

# 20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

m = np.array([[1, 2, 3], [4, 5, 6]])

m.shape




(2, 3)